config/routes.rb
Rails.application.routes.draw do
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  root 'pages#landing'
  get 'home', to: 'pages#home'
  resources :admins do
    resources :students
    resources :instructors
    resources :courses
    resources :cohorts
  end
  delete '/admins/:admin_id/cohorts/:cohort_id/student/:id', to: 'cohorts#remove_student', as: 'remove_student'
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_and_belongs_to_many :students
  belongs_to :instructor
  belongs_to :course
  validates :name, presence: true
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def new
    @admin = Admin.find(params[:admin_id])
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.valid?
      @cohort.save
      redirect_to admin_cohort_path(id: @cohort.id)
    else
      p @cohort.errors
      p "Failed"
      redirect_to new_admin_cohort_path
    end
  end

  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def edit
    @admin = Admin.find(params[:admin_id])
    @cohort = Cohort.find(params[:id])
  end

  def update
    @cohort = Cohort.find(params[:id])
    if @cohort.update_attributes(cohort_params)
      redirect_to admin_cohort_path
    else
      redirect_to edit_admin_cohort_path(id: @cohort.id)
    end
  end

  def destroy
    @cohort = Cohort.find(params[:id])
    @cohort.destroy
  end

  def remove_student
    @cohort = Cohort.find(params[:cohort_id])
    @student = Student.find(params[:id])
    @cohort.students.delete(@student)
      respond_to do |format|
        format.js
      end
  end


  private

  def cohort_params
    params.require(:cohort).permit(:name, :start, :end, :course_id, :instructor_id, student_ids:[])
  end

end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/destroy.js.erb
console.log('Cohort deleted from system');
var row = document.getElementById("cohort-<%= @cohort.id %>");
row.style.display = 'none';

app/views/cohorts/edit.html.erb
<%= render "shared/navbar" %>
<div class="header animated slideInDown">
  <h1><%= @cohort.name %></h1>
</div>
<div class="edit animated zoomIn">
  <div id="back_button">
    <%= link_to admin_cohort_path do %>
      <i class="fas fa-times"></i>
    <% end %>
  </div>
  <%= form_for ([@admin, @cohort]) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :start %>
    <%= f.date_field :start %><br>
    <%= f.label :end %>
    <%= f.date_field :end %><br>

    <%= collection_select(:cohort, :course_id, Course.all, :id, :name) %>
    <%= collection_select(:cohort, :instructor_id, Instructor.all, :id, :name) %>
    <h4>Students:</h4>
    <div id="student_boxes">
      <%= f.collection_check_boxes(:student_ids, Student.all, :id, :name) do |b| %>
        <div> <%= b.check_box %><%= b.label { b.text } %></div>
      <% end %>
    </div>
    <%= f.submit 'Save changes'%>
  <% end %>
</div>

app/views/cohorts/index.html.erb
<%= render "shared/cohort_header"%>
<%= render "shared/navbar" %>
<div class="container animated zoomIn" id="cohort_list">
  <div class="row" id="cohort_headers">
    <div class="col-sm column_header">
      Cohort
    </div>
    <div class="col-sm column_header">
      Course
    </div>
    <div class="col-sm-2 column_header">
      Start
    </div>
    <div class="col-sm-2 column_header">
      End
    </div>
    <div class="col-sm-1 column_header">
    </div>
  </div>
  <% @cohorts.each do |c| %>
    <div class="row" id="cohort-<%= c.id %>">
      <div class="col-sm">
      <%= link_to c.name, admin_cohort_path(id: c.id)%>
      </div>
      <div class="col-sm">
        <% if c.course %>
          <%= link_to c.course.name, admin_course_path(id: c.course_id) %>
        <% else %>
          No course assigned
        <% end %>
      </div>
      <div class="col-sm-2">
        <%= c.start.strftime('%m/%d/%y') %>
      </div>
      <div class="col-sm-2">
        <%= c.end.strftime('%m/%d/%y') %>
      </div>
      <div class="col-sm-1">
        <span class="edit_link"><%= link_to "Edit", edit_admin_cohort_path(id: c.id) %></span>
        <span class="delete_link"><%= link_to "Delete", admin_cohort_path(id: c.id), remote: true, method: :delete, data: { confirm: 'Are you sure? This action is permanent.'} %></span>
      </div>
    </div>
  <% end %>
</div>

<div class="new animated zoomIn">
  <%= link_to 'New', new_admin_cohort_path %>
</div>

app/views/cohorts/new.html.erb
<%= render "shared/navbar" %>
<div class="header animated slideInDown">
  <h1>New Cohort</h1>
</div>
<div class="edit animated zoomIn">
  <%= form_for ([@admin, @cohort]) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :start %>
    <%= f.date_field :start %><br>
    <%= f.label :end %>
    <%= f.date_field :end %><br>

    <%= f.label :students %>
    <div id="student_boxes">
      <%= f.collection_check_boxes(:student_ids, Student.all, :id, :name) do |b| %>
        <div> <%= b.check_box %><%= b.label { b.text } %></div>
      <% end %>
    </div>

    <%= f.label :instructor %>
    <%= collection_select(:cohort, :instructor_id, Instructor.all, :id, :name) %><br>

    <%= f.label :course %>
    <%= collection_select(:cohort, :course_id, Course.all, :id, :name) %><br>

    <%= f.submit 'Submit'%>
  <% end %>
</div>

app/views/cohorts/remove_student_from_cohort.js.erb
console.log('Deleted student');

app/views/cohorts/show.html.erb
<%= render "shared/navbar" %>
<div class="header animated slideInDown">
  <h1><%= @cohort.name %></h1>
</div>
<div class="profile animated zoomIn">
  <div id="edit_button">
    <%= link_to edit_admin_cohort_path do %>
      <i class="fas fa-pen"></i>
    <% end %>
  </div>
  <div class="profile_photo" id="cohort_info">
    <h2>Cohort Start:</h2>
    <%= @cohort.start.strftime("%B%e, %Y") %>
    <h2>Cohort End:</h2>
    <%= @cohort.end.strftime("%B%e, %Y") %>
  </div>
  <div class="profile_info">
    <h2>Course</h2>
    <ul>
    <% if @cohort.course %>
      <li><%= link_to @cohort.course.name, admin_course_path(id: @cohort.course.id) %></li>
    <% else %>
      <h4>No course to show</h4>
    <% end %>
    </ul>
    <h2>Instructor</h2>
    <ul>
    <% if @cohort.instructor %>
      <li><%= link_to @cohort.instructor.name, admin_instructor_path(id: @cohort.instructor_id) %></li>
    <% else %>
      <h4>No instructor assigned</h4>
    <% end %>
    </ul>
  </div>
  <div class="profile_cohorts">
    <h2>Students</h2>
    <ul>
    <% if !@cohort.students.empty? %>
      <% @cohort.students.each do |s| %>
        <li><%= link_to s.name, admin_student_path(id: s.id) %>
        <%= link_to remove_student_path(cohort_id: @cohort.id, id: s), remote: true, method: :delete, data: { confirm: 'You sure?' } do %>
          <span><i class="fas fa-times fa-xs"></i></span>
        <%end%>
      </li>
      <% end %>
    <% else %>
      <h4>No students to show</h4>
    <% end %>
    </ul>
  </div>
</div>