config/routes.rb
Rails.application.routes.draw do
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  root 'pages#landing'
  get 'home', to: 'pages#home'
  resources :admins do
    resources :students
    resources :instructors
    resources :courses
    resources :cohorts
  end
  delete '/admins/:admin_id/cohorts/:cohort_id/student/:id', to: 'cohorts#remove_student', as: 'remove_student'
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_one_attached :avatar
  validates :password, presence: true, length: { minimum: 6 }

  def name
    name = self.first_name + " " + self.last_name
    return name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_and_belongs_to_many :students
  belongs_to :instructor
  belongs_to :course
  validates :name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
  validates :name, presence: true
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_one_attached :avatar
  has_many :cohorts
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, inclusion: {in: 1..150, message: 'Must be between 1 and 150.'}
  validates :salary, numericality: { greater_than_or_equal_to: 0 }
  def name
    name = self.first_name + " " + self.last_name
    return name
  end
end

app/models/student.rb
class Student < ApplicationRecord
  has_one_attached :avatar
  has_and_belongs_to_many :cohorts
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, inclusion: {in: 1..150, message: 'Must be between 1 and 150.'}

  def name
    name = self.first_name + " " + self.last_name
    return name
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :superuser_check, only: [:index]

  def show
    @admin = Admin.find(params[:id])
  end

  def new
    @admin = Admin.new
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def index
    @admin = Admin.all
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.valid?
      @admin.save
      log_in @admin
      redirect_to @admin
    else
      p @admin.errors
      p "Failed"
      render 'new'
    end
  end

  def update
    @admin = Admin.find(params[:id])
    if @admin.update_attributes(admin_params)
      redirect_to admin_path
    else
      redirect_to edit_admin_path(id: @admin.id)
    end
  end

  def destroy
    @admin = Admin.find(session[:user_id])
    log_out
    @admin.destroy
    redirect_to root_url
  end

  private

    def admin_params
      params.require(:admin).permit(:first_name, :last_name, :email, :password, :avatar)
    end

    def superuser_check
      unless current_user == Admin.find_by(email: 'masterhand@smash.com')
        redirect_to admin_path
      end
    end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def new
    @admin = Admin.find(params[:admin_id])
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.valid?
      @cohort.save
      redirect_to admin_cohort_path(id: @cohort.id)
    else
      p @cohort.errors
      p "Failed"
      redirect_to new_admin_cohort_path
    end
  end

  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def edit
    @admin = Admin.find(params[:admin_id])
    @cohort = Cohort.find(params[:id])
  end

  def update
    @cohort = Cohort.find(params[:id])
    if @cohort.update_attributes(cohort_params)
      redirect_to admin_cohort_path
    else
      redirect_to edit_admin_cohort_path(id: @cohort.id)
    end
  end

  def destroy
    @cohort = Cohort.find(params[:id])
    @cohort.destroy
  end

  def remove_student
    @cohort = Cohort.find(params[:cohort_id])
    @student = Student.find(params[:id])
    @cohort.students.delete(@student)
      respond_to do |format|
        format.js
      end
  end


  private

  def cohort_params
    params.require(:cohort).permit(:name, :start, :end, :course_id, :instructor_id, student_ids:[])
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
    @admin = Admin.find(params[:admin_id])
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.valid?
      @course.save
      redirect_to admin_course_path(id: @course.id)
    else
      p @course.errors
      p "Failed"
      redirect_to new_admin_course_path
    end
  end

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def edit
    @admin = Admin.find(params[:admin_id])
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      redirect_to admin_course_path
    else
      redirect_to edit_admin_course_path(id: @course.id)
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
  end


  private

  def course_params
    params.require(:course).permit(:name, :hours)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login
  before_action :logged_out, only: [:landing]

  def home
  end

  def landing
  end

  private

  def logged_out
    if session[:user_id] != nil
      redirect_to home_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def create
    user = Admin.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to home_url
    else
      flash[:alert] = "Incorrect email or password"
      redirect_to root_url
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

 def log_in(user)
   session[:user_id] = user.id
 end

 def current_user
   @current_user ||= Admin.find_by(id: session[:user_id]) if session[:user_id]
 end

 def logged_in?
   !current_user.nil?
 end

 def log_out
   session.delete(:user_id)
   @current_user = nil
 end


end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/edit.html.erb
<%= render "shared/navbar" %>
<div class="header animated slideInDown">
  <h1><%= @admin.name %></h1>
</div>
<div class="edit" id="edit_admin">
  <div id="back_button">
    <%= link_to admin_path do %>
      <i class="fas fa-times"></i>
    <% end %>
  </div>
  <%= form_for (@admin) do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
    <%= f.label :avatar %>
    <%= f.file_field :avatar, direct_upload: true %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>
    <%= f.label 'Re-enter' %>
    <%= f.password_field :password_confirmation %><br>
    <%= f.submit 'Submit'%>
  <% end %>

</div>

app/views/admins/index.html.erb
<%= render "shared/admin_header" %>
<%= render "shared/navbar" %>
<div class="container animated zoomIn">
  <% @admin.each do |a| %>
    <%= a.name %> | <%= a.email %> | <span class="delete_link"><%= link_to 'Delete', admin_path(id: a.id), method: :delete, data: { confirm: 'Are you sure? This action is permanent.'} %></span><br>
  <% end %>
</div>
<br>
<%= link_to 'Back', current_user %>

app/views/admins/new.html.erb
<%= render "shared/navbar" %>
<div class="header animated slideInDown">
  <h1>New Administrator</h1>
</div>

<div class="edit">
  <%= form_for (@admin) do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br>
    <%= f.label :avatar %>
    <%= f.file_field :avatar, direct_upload: true %><br>
    <%= f.submit 'Submit'%>
  <% end %>

</div>

app/views/admins/show.html.erb
<%= render "shared/navbar" %>
<div class="header animated slideInDown">
  <h1><%= @admin.name %></h1>
</div>
<div class="edit" id="show_admin">
  <% if @admin.avatar.attached? %>
    <div class="admin_photo"><%= image_tag(@admin.avatar, width: 200) %></div>
  <% else %>
    <div class="placeholder_image"></div>
  <% end %>
  <div id="edit_button">
    <%= link_to edit_admin_path do %>
      <i class="fas fa-pen"></i>
    <% end %>
  </div>
  <div class="profile_info" id="admin_profile_info">
    <h2><%= @admin.name %></h2>
    <h3><%= @admin.email %></h3>
  </div>
</div>

<div id="new_admin_button"><%= link_to 'New', new_admin_path %></div>
<div id="delete_admin_button"><%= link_to 'Delete', admin_path, method: :delete, data: { confirm: 'Are you sure? This action is permanent.'} %></div>
<% if current_user == Admin.find_by(email: 'masterhand@smash.com') %>
  <div id="admin_index_button"><%= link_to 'Admins', admins_path %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminPanel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Audiowide|Yellowtail|Didact+Gothic" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="options_grid">
  <div class="animated slideInLeft" id="cohorts"><%= link_to 'Cohorts', admin_cohorts_path(session[:user_id]) %></div>
  <div class="animated slideInDown" id="students"><%= link_to 'Students', admin_students_path(session[:user_id]) %></div>
  <div class="animated slideInUp" id="courses"><%= link_to 'Courses', admin_courses_path(session[:user_id]) %></div>
  <div class="animated slideInRight" id="instructors"><%= link_to 'Instructors', admin_instructors_path(session[:user_id]) %></div>
</div>

app/views/pages/landing.html.erb
<div class="logo">
  <div id="smash"><h1>Super Smash</h1></div>
  <div class="animated bounceInRight delay-1s" id="academy"><h1>ACADEMY</h1></div>
</div>
<% if flash[:alert]%>
  <div class="error"><%= flash[:alert]%></div>
<% end %>
<div id="landing">
  <%= form_tag login_path do |form| %>
    <%= text_field_tag :email, nil, placeholder: 'test@test.com', value: 'test@test.com' %><br>
    <%= password_field_tag :password, nil, placeholder: '123456', value: '123456' %><br>
    <%= submit_tag 'Enter' %>
  <% end %>
</div>

app/views/shared/_admin_header.html.erb
<div class="header animated slideInDown">
  <h1>Administrator</h1>
</div>

app/views/shared/_cohort_header.html.erb
<div class="header animated slideInDown">
  <h1>Cohorts</h1>
</div>

app/views/shared/_course_header.html.erb
<div class="header animated slideInDown">
  <h1>Courses</h1>
</div>

app/views/shared/_instructor_header.html.erb
<div class="header animated slideInDown">
  <h1>Instructors</h1>
</div>

app/views/shared/_navbar.html.erb
<div id="navbar">
  <div id="logout"><%= link_to logout_path do %>
    <i class="fas fa-power-off"></i>
    <% end %>
  </div>
  <div id="home"><%= link_to home_path do %>
    <i class="fas fa-home"></i>
    <% end %>
  </div>
  <div id="cohorts"><%= link_to 'Cohorts', admin_cohorts_path(session[:user_id]) %></div>
  <div id="courses"><%= link_to 'Courses', admin_courses_path(session[:user_id]) %></div>
  <div id="students"><%= link_to 'Students', admin_students_path(session[:user_id]) %></div>
  <div id="instructors"><%= link_to 'Instructors', admin_instructors_path(session[:user_id]) %></div>
  <div class="subheader">
    <% user = Admin.find(session[:user_id]) %>
    <%= link_to user.first_name, admin_path(user) %>
  </div>
</div>

app/views/shared/_student_header.html.erb
<div class="header animated slideInDown">
  <h1>Students</h1>
</div>