config/routes.rb
Rails.application.routes.draw do
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  root 'pages#landing'
  get 'home', to: 'pages#home'
  resources :admins do
    resources :students
    resources :instructors
    resources :courses
    resources :cohorts
  end
  delete '/admins/:admin_id/cohorts/:cohort_id/student/:id', to: 'cohorts#remove_student', as: 'remove_student'
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_one_attached :avatar
  has_many :cohorts
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, inclusion: {in: 1..150, message: 'Must be between 1 and 150.'}
  validates :salary, numericality: { greater_than_or_equal_to: 0 }
  def name
    name = self.first_name + " " + self.last_name
    return name
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def new
    @admin = Admin.find(params[:admin_id])
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.valid?
      @instructor.save
      redirect_to admin_instructor_path(id: @instructor.id)
    else
      p @instructor.errors
      p "Failed"
      redirect_to new_admin_instructor_path
    end
  end

  def index
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def edit
    @admin = Admin.find(params[:admin_id])
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])
    if @instructor.update_attributes(instructor_params)
      redirect_to admin_instructor_path
    else
      redirect_to edit_admin_instructor_path(id: @instructor.id)
    end
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
  end

  private

  def instructor_params
    params.require(:instructor).permit(:first_name, :last_name, :email, :age, :education, :salary, :avatar)
  end
end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/destroy.js.erb
console.log('Instructor deleted from system');
var row = document.getElementById("instructor-<%= @instructor.id %>");
row.style.display = 'none';

app/views/instructors/edit.html.erb
<%= render "shared/navbar" %>
<div class="header animated slideInDown">
  <h1><%= @instructor.name %></h1>
</div>
<div class="edit animated zoomIn">
  <div id="back_button">
    <%= link_to admin_instructor_path do %>
      <i class="fas fa-times"></i>
    <% end %>
  </div>
  <%= form_for ([@admin, @instructor]) do |f| %>
    <%= f.file_field :avatar, direct_upload: true %><br>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br>
    <%= f.label :age %>
    <%= f.number_field :age %><br>
    <%= f.label :education %>
    <%= f.select :education, ["", "High School", "Bachelor's Degree", "Master's Degree", "Ph.D"] %>
    <%= f.label :salary %>
    <%= f.number_field :salary %><br>

    <%= f.submit 'Submit'%>
  <% end %>
</div>

app/views/instructors/index.html.erb
<%= render "shared/instructor_header" %>
<%= render "shared/navbar" %>
<div class="container animated zoomIn" id="instructor_list">
  <div class="row" id="instructor_headers">
    <div class="col-sm-2 column_header">
      First
    </div>
    <div class="col-sm-3 column_header">
      Last
    </div>
    <div class="col-sm-1 column_header">
      Age
    </div>
    <div class="col-sm-1 column_header">
      Salary
    </div>
    <div class="col-sm column_header">
      Education
    </div>
  </div>
  <% @instructors.each do |i| %>
  <div class="row" id="instructor-<%=i.id%>">
      <div class="col-sm">
      <%= link_to i.first_name, admin_instructor_path(id: i.id) %>
      </div>
      <div class="col-sm">
        <%= link_to i.last_name, admin_instructor_path(id: i.id) %>
      </div>
      <div class="col-sm-1">
        <%= i.age %>
      </div>
      <div class="col-sm-1">
        $<%= i.salary %>
      </div>
      <div class="col-sm">
        <%= i.education %>
      </div>
      <div class="col-sm">
        <span class="edit_link"><%= link_to "Edit", edit_admin_instructor_path(id: i.id) %></span>
        <span class="delete_link"><%= link_to "Delete", admin_instructor_path(id: i.id), remote: true, method: :delete, data: { confirm: 'Are you sure? This action is permanent.'} %></span>
      </div>
    </div>
    <% end %>
</div>

<div class="new animated zoomIn">
  <%= link_to 'New', new_admin_instructor_path %>
</div>

app/views/instructors/new.html.erb
<%= render "shared/navbar" %>
<div class="header animated slideInDown">
  <h1>New Instructor</h1>
</div>
<div class="edit animated zoomIn">
  <%= form_for ([@admin, @instructor]) do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br>
    <%= f.label :age %>
    <%= f.number_field :age %><br>
    <%= f.label :education %>
    <%= f.select :education, ["", "High School", "Bachelor\'s Degree", "Master\'s Degree", "Ph.D"] %><br>
    <%= f.label :salary %>
    <%= f.number_field :salary %><br>
    <%= f.label :avatar %>
    <%= f.file_field :avatar, direct_upload: true %><br>

    <%= f.submit 'Submit'%>
  <% end %>
</div>

app/views/instructors/show.html.erb
<%= render "shared/navbar" %>
<div class="header animated slideInDown">
  <h1><%= @instructor.name %></h1>
</div>
<div class="profile animated zoomIn">
  <div id="edit_button">
    <%= link_to edit_admin_instructor_path do %>
      <i class="fas fa-pen"></i>
    <% end %>
  </div>
  <div class="profile_photo">
    <% if @instructor.avatar.attached? %>
      <%= image_tag(@instructor.avatar, width: 200) %>
    <% else %>
      <div class="placeholder_image"></div>
    <% end %>
  </div>
  <div class="profile_info">
    <h2>Stats</h2>
    <h3>Age: <%= @instructor.age %></h3>
    <h3>Education: <%= @instructor.education %></h3>
  </div>
  <div class="profile_cohorts">
    <h2>Cohorts</h2>
    <% if !@instructor.cohorts.empty? %>
    <ul>
      <% @instructor.cohorts.each do |c| %>
        <li><%= link_to c.name, admin_cohort_path(id: c.id) %></li>
      <% end %>
    </ul>
    <% else %>
      <h3>No cohorts to show</h3>
    <% end %>
  </div>
</div>